apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-project
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - environment-dev
  selector:
    matchLabels:
      app: devops-project
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
